url: "https://lambda.cyou" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "HANABI的世界" # the name of your site, e.g. ACME Corp.
